package Acme::CPANLists::Import::PERLANCAR::Advent::2014_12_04;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://blogs.perl.org/users/perlancar/2014/12/day-4-date-calculator-shell-appdatecalc.html] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Reply"},{module=>"Reply::Plugin::DataDumpColor"}],summary=>"Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 04)"});

1;
# ABSTRACT: Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 04)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://blogs.perl.org/users/perlancar/2014/12/day-4-date-calculator-shell-appdatecalc.html> (retrieved on 2016-11-07). Visit the URL for the full contents.

