package Acme::CPANLists::Import::PERLANCAR::Advent::2014_12_10;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://blogs.perl.org/users/perlancar/2014/12/day-10-finding-modules-path-and-more-modulepathmore.html] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Module::List"},{module=>"Module::Path"},{module=>"Module::Path::More"}],summary=>"Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 10)"});

1;
# ABSTRACT: Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 10)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://blogs.perl.org/users/perlancar/2014/12/day-10-finding-modules-path-and-more-modulepathmore.html> (retrieved on 2016-11-07). Visit the URL for the full contents.

