package Acme::CPANLists::Import::PERLANCAR::Advent::2014_12_07;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://blogs.perl.org/users/perlancar/2014/12/day-7-set-screensaver-timeout-from-the-command-line-appsetscreensavertimeout.html] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"App::fsql"}],summary=>"Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 07)"});

1;
# ABSTRACT: Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 07)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://blogs.perl.org/users/perlancar/2014/12/day-7-set-screensaver-timeout-from-the-command-line-appsetscreensavertimeout.html> (retrieved on 2016-11-07). Visit the URL for the full contents.

