package Acme::CPANLists::Import::PERLANCAR::Advent::2014_12_09;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://blogs.perl.org/users/perlancar/2014/12/day-9-set-operations-with-files-appsetop.html] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"App::setop"}],summary=>"Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 09)"});

1;
# ABSTRACT: Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 09)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://blogs.perl.org/users/perlancar/2014/12/day-9-set-operations-with-files-appsetop.html> (retrieved on 2016-11-07). Visit the URL for the full contents.

