package Acme::CPANLists::Import::PERLANCAR::Advent::2014;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://blogs.perl.org/users/perlancar/2014/12/perlancars-2014-advent-calendar.html] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"JSON::Path"},{module=>"DBIx::Compare"},{module=>"Reply"},{module=>"Reply::Plugin::DataDumpColor"},{module=>"Perinci::CmdLine"},{module=>"Data::Dump"},{module=>"File::chdir"},{module=>"File::umask"},{module=>"Locale::Tie"},{module=>"Unix::setuid"},{module=>"App::Stopwatch"},{module=>"Module::List"},{module=>"Module::Path"},{module=>"Module::Path::More"},{module=>"App::DistUtils"},{module=>"App::DzilUtils"},{module=>"App::GitUtils"},{module=>"App::PMUtils"},{module=>"App::PlUtils"},{module=>"App::ProgUtils"},{module=>"Dist::Zilla::Plugin::Run"},{module=>"Dist::Zilla::PluginBundle::Author::PERLANCAR"},{module=>"Proc::ChildError"},{module=>"Games::Word::Wordlist::Country"},{module=>"Games::Word::Wordlist::CountrySingleWord"},{module=>"Games::Word::Wordlist::Enable"},{module=>"Games::Word::Wordlist::KBBI"},{module=>"Games::Word::Wordlist::SGB"},{module=>"Dist::Zilla"},{module=>"Dist::Zilla::Plugin::GenShellCompletion"},{module=>"Getopt::Long"},{module=>"Getopt::Long::Complete"},{module=>"Riap"},{module=>"Rinci"},{module=>"Proc::Exists"},{module=>"Proc::Find"},{module=>"File::Unsaved"},{module=>"Devel::NYTProf"},{module=>"Devel::STrace"},{module=>"Devel::TraceCalls"},{module=>"Devel::TraceSubs"},{module=>"Hook::LexWrap"},{module=>"Log::Any"},{module=>"Runops::Trace"},{module=>"File::Temp"},{module=>"IOD"},{module=>"Test::DatabaseRow"},{module=>"Test::WithDB"},{module=>"String::Wildcard::DOS"},{module=>"String::Wildcard::SQL"},{module=>"Sys::Run::Safer"},{module=>"chart"},{module=>"Games::ArrangeNumber"},{module=>"Games::Hangman"}],summary=>"Modules mentioned in PERLANCAR's 2014 advent calendar article series"});

1;
# ABSTRACT: Modules mentioned in PERLANCAR's 2014 advent calendar article series

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://blogs.perl.org/users/perlancar/2014/12/perlancars-2014-advent-calendar.html> (retrieved on 2016-11-07). Visit the URL for the full contents.

