package Acme::CPANLists::Import::PERLANCAR::Advent::2014_12_11;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://blogs.perl.org/users/perlancar/2014/12/day-11-tab-completion-galore-apppmplprogdzilgitutils.html] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"App::DistUtils"},{module=>"App::DzilUtils"},{module=>"App::GitUtils"},{module=>"App::PMUtils"},{module=>"App::PlUtils"},{module=>"App::ProgUtils"},{module=>"Dist::Zilla::Plugin::Run"},{module=>"Dist::Zilla::PluginBundle::Author::PERLANCAR"}],summary=>"Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 11)"});

1;
# ABSTRACT: Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 11)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://blogs.perl.org/users/perlancar/2014/12/day-11-tab-completion-galore-apppmplprogdzilgitutils.html> (retrieved on 2016-11-07). Visit the URL for the full contents.

