package Acme::CPANLists::Import::PERLANCAR::Advent::2014_12_15;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://blogs.perl.org/users/perlancar/2014/12/day-15-words-on-cpan-appwordlist.html] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Games::Word::Wordlist::Country"},{module=>"Games::Word::Wordlist::CountrySingleWord"},{module=>"Games::Word::Wordlist::Enable"},{module=>"Games::Word::Wordlist::KBBI"},{module=>"Games::Word::Wordlist::SGB"}],summary=>"Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 15)"});

1;
# ABSTRACT: Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 15)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://blogs.perl.org/users/perlancar/2014/12/day-15-words-on-cpan-appwordlist.html> (retrieved on 2016-11-07). Visit the URL for the full contents.

