package Acme::CPANLists::Import::PERLANCAR::Advent::2014_12_19;

# DATE
# VERSION

our @Module_Lists = ({description=>"This list is generated by extracting module names mentioned in [http://blogs.perl.org/users/perlancar/2014/12/day-19-tracing-your-perl-programs-execution-appplstrace.html] (retrieved on 2016-11-07). Visit the URL for the full contents.",entries=>[{module=>"Devel::NYTProf"},{module=>"Devel::STrace"},{module=>"Devel::TraceCalls"},{module=>"Devel::TraceSubs"},{module=>"Hook::LexWrap"},{module=>"Log::Any"},{module=>"Runops::Trace"}],summary=>"Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 19)"});

1;
# ABSTRACT: Modules mentioned in PERLANCAR's 2014 advent calendar article series (day 19)

=head1 DESCRIPTION

This module is generated by extracting module names mentioned in L<http://blogs.perl.org/users/perlancar/2014/12/day-19-tracing-your-perl-programs-execution-appplstrace.html> (retrieved on 2016-11-07). Visit the URL for the full contents.

